name: PY3
channels:
  - pytorch
  - intel
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - _tflow_select=2.1.0=gpu
  - absl-py=0.9.0=py36_0
  - asn1crypto=1.3.0=py36_0
  - astor=0.8.0=py36_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - blinker=1.4=py36_0
  - boto=2.49.0=py36_0
  - boto3=1.14.20=pyh9f0ad1d_0
  - botocore=1.17.20=pyh9f0ad1d_0
  - bzip2=1.0.8=h516909a_2
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.12.5=ha878542_0
  - cachetools=3.1.1=py_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.12.5=py36h5fab9bb_1
  - cffi=1.14.0=py36h2e261b9_0
  - chardet=3.0.4=py36_1003
  - click=7.0=py36_0
  - cloudpickle=1.6.0=py_0
  - cryptography=2.8=py36h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - dill=0.3.2=pyh9f0ad1d_0
  - docutils=0.15.2=py36_0
  - entrypoints=0.3=py36_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.2=h167e202_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h516909a_1002
  - fsspec=0.8.7=pyhd8ed1ab_0
  - future=0.18.2=py36h5fab9bb_3
  - gast=0.2.2=py36_0
  - gensim=3.8.0=py36h962f231_0
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=hb3b607b_0
  - gnutls=3.6.5=hd3a4fd2_1002
  - google-api-core=1.16.0=py36_1
  - google-auth=1.11.2=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-cloud-core=1.4.0=pyh9f0ad1d_0
  - google-cloud-storage=1.30.0=pyh9f0ad1d_0
  - google-crc32c=1.0.0=py36h9c36872_1
  - google-pasta=0.1.8=py_0
  - google-resumable-media=1.1.0=pyh9f0ad1d_0
  - googleapis-common-protos=1.52.0=py36h9f0ad1d_0
  - graphite2=1.3.13=hf484d3e_1000
  - graphviz=2.40.1=h21bd128_2
  - grpcio=1.27.2=py36hf8bcb03_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.10.0=py36h7918eee_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h211956c_0
  - idna=2.8=py36_0
  - imageio=2.8.0=py_0
  - imageio-ffmpeg=0.4.1=py_0
  - importlib_metadata=1.5.0=py36_0
  - intel-openmp=2020.0=166
  - intelpython=2020.1=0
  - ipykernel=5.1.4=py36h39e3cac_0
  - ipython=7.12.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.16.0=py36_0
  - jinja2=2.11.1=py_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=0.14.1=py_0
  - jpeg=9b=habf39ab_1
  - jsonschema=3.2.0=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.3.4=py36_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.1=py36_0
  - kaggle=1.5.6=py36_1
  - keras-applications=1.0.8=py_0
  - keras-base=2.3.1=py36_0
  - keras-gpu=2.3.1=0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py36he6710b0_0
  - lame=3.100=h14c3975_1001
  - ld_impl_linux-64=2.33.1=h53a641e_8
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libcrc32c=1.1.1=he1b5a44_2
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=14_mkl
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.14.0=h8c45485_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markdown=3.1.1=py36_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib-base=3.1.3=py36hef1b27d_0
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2019.5=281
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - moviepy=1.0.1=py_0
  - multiprocess=0.70.10=py36h8c4c3a4_0
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=hf484d3e_1002
  - nettle=3.4.1=h1bed415_1002
  - ninja=1.10.0=hdb11119_1
  - notebook=6.0.3=py36_0
  - numpy=1.18.1=py36h4f9e942_0
  - numpy-base=1.18.1=py36hde5b4d6_1
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py36_0
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1h=h516909a_0
  - opt_einsum=3.1.0=py_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.0.1=py36h0573a6f_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - pango=1.42.4=h049681c_0
  - parso=0.6.1=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=7.0.0=py36hb39fc2d_0
  - pip=20.0.2=py_2
  - pixman=0.38.0=h516909a_1003
  - proglog=0.1.9=py_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - ptyprocess=0.6.0=py36_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.19=py36_0
  - pydicom=1.4.2=py_0
  - pydot=1.4.1=py36_1001
  - pygments=2.5.2=py_0
  - pyjwt=1.7.1=py36_0
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py36h22d08a2_1
  - pyrsistent=0.15.7=py36h7b6447c_0
  - pysocks=1.7.1=py36_0
  - python=3.6.10=h9d8adfe_1009_cpython
  - python-dateutil=2.8.1=py_0
  - python-slugify=4.0.0=py_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.4.0=py3.6_cuda10.1.243_cudnn7.6.3_0
  - pytorch-lightning=1.2.3=pyhd8ed1ab_0
  - pytz=2019.3=py_0
  - pyyaml=5.3=py36h7b6447c_0
  - pyzmq=18.1.1=py36he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.6.0=py_1
  - readline=8.0=hf8c457e_0
  - regex=2020.6.8=py36h8c4c3a4_0
  - requests=2.22.0=py36_1
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.0=py_0
  - s3transfer=0.3.3=py36h9f0ad1d_1
  - sacremoses=0.0.43=pyh9f0ad1d_0
  - scikit-learn=0.22.2.post1=py36hcdab131_0
  - scipy=1.4.1=py36h2d22cac_3
  - seaborn=0.10.0=py_0
  - send2trash=1.5.0=py36_0
  - setuptools=46.0.0=py36_0
  - sip=4.19.13=py36he6710b0_0
  - six=1.14.0=py36_0
  - smart_open=2.0.0=pyh9f0ad1d_0
  - sqlite=3.30.1=hcee41ef_0
  - tensorboard=2.4.1=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tensorboardx=2.1=py_0
  - tensorflow=2.1.0=gpu_py36h2e5cdaa_0
  - tensorflow-base=2.1.0=gpu_py36h6c5654b_0
  - tensorflow-estimator=2.1.0=pyhd54b08b_0
  - tensorflow-gpu=2.1.0=h0d30ee6_0
  - tensorflow-probability=0.8.0=py_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hed695b0_0
  - torchvision=0.5.0=py36_cu101
  - tornado=6.0.3=py36h7b6447c_3
  - tqdm=4.45.0=pyh9f0ad1d_0
  - traitlets=4.3.3=py36_0
  - transformers=2.1.1=py_0
  - unidecode=1.1.1=py_0
  - urllib3=1.24.3=py36_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py36_1
  - werkzeug=1.0.0=py_0
  - wheel=0.34.2=py_1
  - widgetsnbextension=3.5.1=py36_0
  - wrapt=1.11.2=py36h7b6447c_0
  - x264=1!152.20180806=h14c3975_0
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h96e3832_1
  - zeromq=4.3.1=he6710b0_3
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - argcomplete==1.12.2
    - bz2file==0.98
    - configparser==5.0.1
    - continuum==0.1
    - corenlp-protobuf==3.8.0
    - crcmod==1.7
    - cycler==0.10.0
    - cython==0.29.21
    - docker-pycreds==0.4.0
    - efficientnet==1.0.0
    - efficientnet-pytorch==0.6.3
    - fasteners==0.16
    - filelock==3.0.12
    - gcs-oauth2-boto-plugin==2.7
    - gdown==3.10.3
    - gitdb==4.0.5
    - gitpython==3.1.11
    - google-apitools==0.5.31
    - google-reauth==0.1.1
    - googledrivedownloader==0.4
    - graphql-core==3.1.5
    - gsutil==4.59
    - gym==0.18.0
    - higher==0.2.1
    - httplib2==0.19.0
    - image-classifiers==1.0.0
    - imgaug==0.4.0
    - jsonpatch==1.25
    - jsonpointer==2.0
    - keras-vis==0.4.1
    - learn2learn==0.1.5
    - matplotlib==3.2.1
    - mock==2.0.0
    - monotonic==1.5
    - networkx==2.4
    - oauth2client==4.1.3
    - opencv-python-headless==4.2.0.32
    - ordered-set==4.0.2
    - pathtools==0.1.2
    - pbr==5.5.1
    - promise==2.3
    - protobuf==3.14.0
    - psutil==5.8.0
    - pyglet==1.5.0
    - pyu2f==0.1.5
    - pywavelets==1.1.1
    - quadprog==0.1.7
    - retry-decorator==1.1.1
    - scikit-image==0.16.2
    - segmentation-models==1.0.1
    - sentry-sdk==1.3.1
    - shapely==1.7.0
    - shortuuid==1.0.1
    - smmap==3.0.4
    - stanford-corenlp==3.9.2
    - subprocess32==3.5.4
    - tabulate==0.8.7
    - tesserocr==2.5.1
    - text-unidecode==1.3
    - torch==1.4.0
    - torchattacks==1.3
    - torchfile==0.1.0
    - torchmeta==1.6.1
    - torchsummary==1.5.1
    - visdom==0.1.8.9
    - wandb==0.11.1
    - watchdog==1.0.2
    - websocket-client==0.57.0
prefix: /home/hikmat/anaconda3/envs/PY3

